/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#line 1 "test.check"
#include "Functions.h"
#include <string.h>
/*#test correctRomanNumber
	
	char RomanNo[] = "MVXLI";
	ck_assert_int_eq(IpCheck(RomanNo),1);*/
/*#test RomanNoToDecimal
	
	char RomanNo[] = "MDCCXXIV";
	char RomanNo1[] = "MLXLVI";
	ck_assert_int_eq(RomanToDecimal(RomanNo),1724);
	ck_assert_int_eq(RomanToDecimal(RomanNo1),1096);*/
START_TEST(AdditionOrSubtraction)
{
#line 14

	char RomanNo[] = "MDCCXXIV";
	char RomanNo1[] = "MLXLVI";
	int RomanToDecimal1, RomanToDecimal2;
	int operation = 2;//If its 1 then Addition & 2 then Subtraction
	RomanToDecimal1 = RomanToDecimal(RomanNo);
	RomanToDecimal2 = RomanToDecimal(RomanNo1);
	ck_assert_int_eq(AddOrSub(RomanToDecimal1,RomanToDecimal2,operation),628);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, AdditionOrSubtraction);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
